### ISSUE TITLE
Cannot Flash SSD on Xavier NX 16GB 

### ISSUE THREAD

**Issue by patrickpoirier51** [jetsonhacks/bootFromExternalStorage#24]
Hello Jim,

I just received the Xavier NX 16 GB from SeeedStudio 
https://www.seeedstudio.com/Jetson-20-1-H2-p-5329.html
With these features:
Memory 	16 GB 128-bit LPDDR4x @ 59.7GB/s
Storage 	16 GB eMMC

Following your instructions, I tried to flash my SSD drive (500 Gb Western Digital NVMe).
LSUSB :
Bus 001 Device 010: ID 0955:7e19 NVIDIA Corp. APX

Launching the flash utility , I get this message:
Error: Target board not found.

Getting deeper I launch this script:
sudo ./nvautoflash.sh --print_boardid

Result:
[   3.2258 ] 
--- Reading board information succeeded.
Parsing module EEPROM:
--- Parsing board ID (3668) succeeded.
--- Parsing board version (301) succeeded.
--- Parsing board SKU (0003) succeeded.
--- Parsing board REV (B.0) succeeded.
Error: Target board not found.

Looking at the table within the script, there is no reference to this board ID-SKU-REV, so I guess it need to be updated, 
LINE 387
```
#
#                                     BOARDID  BOARDSKU  FAB  BOARDREV
#    --------------------------------+--------+---------+----+---------
#    jetson-agx-xavier-industrial     2888     0008      600  A.0
#    jetson-xavier-nx-devkit-tx2-nx   3636     0001      100  B.0
#    clara-agx-xavier-devkit"         3900     0000      001  C.0
#    jetson-xavier-nx-devkit          3668     0000      100  N/A
#    jetson-xavier-nx-devkit-emmc     3668     0001      100  N/A
#    jetson-nano-devkit               3448     0000      200  N/A
#    jetson-nano-devkit-emmc          3448     0002      400  N/A
#    jetson-nano-2gb-devkit           3448     0003      300  N/A
#    jetson-agx-xavier-devkit (16GB)  2888     0001      400  H.0
#    jetson-agx-xavier-devkit (32GB)  2888     0004      400  K.0
#    jetson-tx2-devkit                3310     1000      B02  N/A
#    jetson-tx2-devkit-tx2i           3489     0000      300  A.0
#    jetson-tx2-devkit-4gb            3489     0888      300  F.0
#    jetson-tx1-devkit                2180     0000      400  N/A
#    --------------------------------+--------+---------+----+---------
#

```
I can try to plug the numbers in but I dont want to brick the board.

**Comment by jetsonhacks** [comment]
Hi Patrick,
This is an older script for use when the SDK Manager did not handle boot from external storage. Newer versions do, you should try that.

**Comment by patrickpoirier51** [comment]
Thanks Jim, I will
