### ISSUE TITLE
[BUG] Error Flashing a New Jetson Orin Nano Developer Kit

### ISSUE THREAD

**Issue by armuren** [jetsonhacks/bootFromExternalStorage#34]
**Describe the issue**
Hi Jim,

Many thanks for the years of excellent work.  I have found your examples very helpful throughout the years. 

I am flashing a new Jetson Orin Nano Developer kit 8GB.  I followed the instructions in the [SSD Install Video](https://www.youtube.com/watch?v=q4fGac-nrTI) pretty closely, and repeated the process twice.  I am getting the following error when I run the flash script.  I didn't change the script in any way, simply cloned the repo, ran the download script which downloaded everything correctly and installed dependencies, and then I ran the flash script.

```
$  ./flash_jetson_external_storage.sh 
....
LOTS OF outputs that is working correctly, then an error
...

cp: cannot stat 
'~/JETSONHACKS/bootFromExternalStorage/R35.3.1/Linux_for_Tegra/rootfs/lib/modules/5.10.104-tegra/kernel/drivers/mtd': No such file or directory
```

**Which version of Ubuntu on the Host machine**
Ubuntu 20.04

**What version of L4T/JetPack**
L4T/JetPack version: R35.3.1

**Which Jetson**
Jetson: Nano Orin Developer Kit 8GB

**To Reproduce**
```
$  ./flash_jetson_external_storage.sh 
```

**Expected behavior**
A Flashed Jetson Orin Nano Developer Kit

**Comment by JetsonHacksNano** [comment]
Did you check to see if the file actually exists? The most likely cause is that the rootfs was corrupt when downloaded and did not expand correctly, or that there was not enough room on the disk to expand the rootfs. This method can use 80GB of disk space.
