### ISSUE TITLE
Issue: Failed to restart nfs-kernel-server.service

### ISSUE THREAD

**Issue by egwheeler** [jetsonhacks/bootFromExternalStorage#35]
When flashing the jetson (AGX Orin 32GB), the flashing process begins then stops abruptly with the following failure:
"Failed to restart nfs-kernel-server.service: Unit proc-fs-nfsd.mount is masked"

This happens for both sda1 and nvme0n1p1. Does this mean the external device/target partition must be mounted? Sorry, pretty new to the Nvidia dev community.

Host machine
Ubuntu version: 20.04.06

L4T/JetPack version: 5.1

**Which Jetson**
Jetson AGX Orin 32G Dev kit

**To Reproduce**
# ./flash_jetson_external_storage.sh -s nvme0n1p1 (Where P1 is an unformatted partition on a 2TB Samsung NVME)
     lsblk
        dev/nvme0n1  (part table-->gpt)
         --> nvme01p1

**Expected behavior**
Expected the jetpack 5.1 to be flashed to the external nvme device on my agx orin dev kit

**Comment by JetsonHacksNano** [comment]
How did you put the Jetson into force recovery mode?
The default is nvme, you might try just:
$ ./flash_jetson_external_storage.sh
Is the SSD formatted?
The error is in the NVIDIA provided scripts, it's difficult to tell what the issue might be.

**Comment by egwheeler** [comment]
Thanks for your comment!

The drive was unformatted but enabled with GPT part_table and so I removed that all together. Then I ran again with command and leaving off the nvme0n0 and just letting it default and it worked.

Thanks again!


> How did you put the Jetson into force recovery mode? The default is nvme, you might try just: $ ./flash_jetson_external_storage.sh Is the SSD formatted? The error is in the NVIDIA provided scripts, it's difficult to tell what the issue might be.

**Comment by jetsonhacks** [comment]
I'm glad you were able to get it to work!
