### ISSUE TITLE
[Error] ./flash_jetson_external_storage.sh: device /dev/nvme0n1 - No such file or directory.

### ISSUE THREAD

**Issue by muse1835** [jetsonhacks/bootFromExternalStorage#38]
**Describe the issue**
Please describe the issue

**Which version of Ubuntu on the Host machine**
Ubuntu version: 20.04

**What version of L4T/JetPack**
L4T/JetPack version: 35.4.1

**Which Jetson**
Jetson: Jetson Xavier AGX

**To Reproduce**
For example, what command line did you run?

./flash_jetson_external_storage.sh 

**Expected behavior**

Error messege...

Error: Could not stat device /dev/nvme0n1 - No such file or directory.
Flash failure

**Additional context**
Add any other context about the problem here

[error.txt](https://github.com/jetsonhacks/bootFromExternalStorage/files/12571159/error.txt)
.

**Comment by muse1835** [comment]
sorry... It works with other SSD.

**Comment by ledinhtri97** [comment]
hello @muse1835 I faced the same issue, what is your other ssd was successful?
