### ISSUE TITLE
[QUESTION] Dual boot source in Jetson AGX Orin

### ISSUE THREAD

**Issue by PHCLenzi** [jetsonhacks/bootFromExternalStorage#39]
**Describe the issue**
My question is: How can I configure the files on the two memory devices (eMMC and USB Stick) so that if the USB Stick is not connected to the Jetson during boot, then the system will boot from the internal eMMC memory device.

I'm currently using Ubuntu 20.04 as the host pc and the Jetson AGX Orin devkit. I used the flash_jetson_external_storage.sh algorithm to flash the system onto a USB Stick and currently the system is being loaded from this USB Stick.

I'm new to this booting process and I know the file ".../boot/extlinux/extlinux.conf" but just changing this file doesn't seem to be enough.

If you need more information to answer my question, please let me know

**Which version of Ubuntu on the Host machine**
Ubuntu version: Ubuntu 20.04 as the host pc

**What version of L4T/JetPack**
L4T/JetPack version: 35.4

**Which Jetson**
Jetson: AGX Orin devkit

**Comment by PHCLenzi** [comment]
Also, how do I change the label of this issue from bug to question?

**Comment by jetsonhacks** [comment]
@PHCLenzi - I believe that you should be able to set the boot order in the UEFI setup. USB first, eMMC and so on.
You should be able to change the bug to question in the Labels category in the sidebar.
You should probably ask on the AGX Orin Jetson forum for a better answer for your question if setting the boot order does not work.

**Comment by PHCLenzi** [comment]
Hallo @jetsonhacks. I had imagined that during the execution of the "bootFromExternalStorage/flash_jetson_external_storage.sh" script, which in turn executes the "nvsdkmanager_flash.sh" script, there were target configuration files to alter the boot process once the kernel and filesystem had already been flashed to removable memory. I would like to know which files are changed during the execution of "bootFromExternalStorage/flash_jetson_external_storage.sh" that alter the booting process. Do you know?

**Comment by jetsonhacks** [comment]
nvsdkmanager_flash.sh creates a bootable image on the host and then flashes it to the Jetson. To my knowledge, there isn't any post processing to change target configuration files or alter the boot process once flashed.
