### ISSUE TITLE
Partition is only 16GB on a 500GB nvme drive

### ISSUE THREAD

**Issue by patrickpoirier51** [jetsonhacks/bootFromExternalStorage#40]
Using the utilities , I cannot specify the size of the partition at UBUNTU startup, it is missing the partition step.
It looks like the script is defaulting to emmc (supposed to be defaulted to nvme ?):

0]: l4t_flash_from_kernel: Starting to create gpt for emmc
Active index file is /mnt/internal/flash.idx
Number of lines is 42
max_index=41
[ 5]: l4t_flash_from_kernel: Successfully create gpt for emmc
[ 5]: l4t_flash_from_kernel: Starting to create gpt for external device
Active index file is /mnt/external/flash.idx
Number of lines is 18
max_index=17
writing item=1, 9:0:primary_gpt, 512, 19968, gpt_primary_9_0.bin, 16896, fixed-<reserved>-0, 6022c5641495b0d9deaa2e0f9542e6c9e532ae17
Writing primary_gpt partition with gpt_primary_9_0.bin
Offset is not aligned to K Bytes, no optimization is applied
dd if=/mnt/external/gpt_primary_9_0.bin of=/dev/nvme0n1 bs=1 skip=0  seek=512 count=16896
16896+0 records in
16896+0 records out
16896 bytes (17 kB, 16 KiB) copied, 0.554922 s, 30.4 kB/s
Writing primary_gpt partition done
Error: The backup GPT table is corrupt, but the primary appears OK, so that will be used.
Warning: Not all of the space available to /dev/nvme0n1 appears to be used, you can fix the GPT to use all of the space (an extra 854614063 blocks) or continue with the current setting? 
Writing secondary_gpt partition with gpt_secondary_9_0.bin
Offset is not aligned to K Bytes, no optimization is applied
dd if=/mnt/external/gpt_secondary_9_0.bin of=/dev/nvme0n1 bs=1 skip=0  seek=62545444352 count=16896
16896+0 records in
16896+0 records out
16896 bytes (17 kB, 16 KiB) copied, 0.535351 s, 31.6 kB/s
Writing secondary_gpt partition done
Error: The backup GPT table is not at the end of the disk, as it should be.  Fix, by moving the backup to the end (and removing the old backup)?
Fix/Ignore? Fix                                                           
Warning: Not all of the space available to /dev/nvme0n1 appears to be used, you can fix the GPT to use all of the space (an extra 854614063 blocks) or continue with the current setting? 
Fix/Ignore? Fix                                                           
Model: WDS500G3X0C-00SJG0 (nvme)
Disk /dev/nvme0n1: 500GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name                       Flags
 1      20.5kB  15.0GB  15.0GB  ext4         APP                        msftdata
 2      15.0GB  15.2GB  134MB                kernel                     msftdata
 3      15.2GB  15.2GB  786kB                kernel-dtb                 msftdata
 4      15.2GB  15.2GB  33.2MB               reserved_for_chain_A_user  msftdata
 5      15.2GB  15.3GB  134MB                kernel_b                   msftdata
 6      15.3GB  15.3GB  786kB                kernel-dtb_b               msftdata
 7      15.3GB  15.4GB  33.2MB               reserved_for_chain_B_user  msftdata
 8      15.4GB  15.5GB  83.9MB               recovery                   msftdata
 9      15.5GB  15.5GB  524kB                recovery-dtb               msftdata
10      15.5GB  15.6GB  105MB                RECROOTFS                  msftdata
11      15.6GB  15.6GB  67.1MB               esp                        boot, esp
12      15.6GB  15.7GB  83.9MB               recovery_alt               msftdata
13      15.7GB  15.7GB  524kB                recovery-dtb_alt           msftdata
14      15.7GB  15.8GB  67.1MB               esp_alt                    msftdata
15      15.8GB  62.5GB  46.8GB               UDA                        msftdata

[ 16]: l4t_flash_from_kernel: Expanding last partition to fill the storage device
[ 16]: l4t_flash_from_kernel: Successfully create gpt for external device

**Comment by SunilDJPro** [comment]
Better manually use gparted and move the efi partition to the last by deleting all unused partitions and resize the root partition. This issue is common on all emmc jetson boards.

Edit: I have followed this exact thing to expand the storage for root partition and it works fine till date on a Xavier NX 16GB emmc board (SeedStudio).

**Comment by patrickpoirier51** [comment]
OK, Thanks for helping
You mean, that after initial installation , I delete all the kernel and recovery partitions ?

**Comment by patrickpoirier51** [comment]
OK, I made it work, here is the new geometry

![Screenshot from 2023-09-26 08-11-04](https://github.com/jetsonhacks/bootFromExternalStorage/assets/12484190/bb0ac32c-f314-460a-89c1-185484a9e8a5)

**Comment by SunilDJPro** [comment]
good but if possible shrink the boot partition to 2 GB and get hold of 63 GB. I was able to do.

**Comment by patrickpoirier51** [comment]
Seems that gparted does not allow for smaller size on a 500 GB drive, anyway I have plenty

**Comment by jetsonhacks** [comment]
If this is for a Jetson Xavier, it is a known NVIDIA bug.

**Comment by altyi** [comment]
@patrickpoirier51 
Hi, do you mind sharing how you did reformate the partitions? I am not able to move the esp partition to the end to expand the root. Thanks.

**Comment by patrickpoirier51** [comment]
@altyi 
Looking at my list above,  You have to delete these partitions:

2 15.0GB 15.2GB 134MB kernel msftdata
3 15.2GB 15.2GB 786kB kernel-dtb msftdata
4 15.2GB 15.2GB 33.2MB reserved_for_chain_A_user msftdata
5 15.2GB 15.3GB 134MB kernel_b msftdata
6 15.3GB 15.3GB 786kB kernel-dtb_b msftdata
7 15.3GB 15.4GB 33.2MB reserved_for_chain_B_user msftdata
8 15.4GB 15.5GB 83.9MB recovery msftdata
9 15.5GB 15.5GB 524kB recovery-dtb msftdata
10 15.5GB 15.6GB 105MB RECROOTFS msftdata

12 15.6GB 15.7GB 83.9MB recovery_alt msftdata
13 15.7GB 15.7GB 524kB recovery-dtb_alt msftdata
14 15.7GB 15.8GB 67.1MB esp_alt msftdata
15 15.8GB 62.5GB 46.8GB UDA msftdata

Then you can move to the end 
11 15.6GB 15.6GB 67.1MB esp boot, esp

and expand
1 20.5kB 15.0GB 15.0GB ext4 APP msftdata
to full space available

**Comment by altyi** [comment]
Thanks for the quick response, I was able to do that after I boot with the sd card and then use gparted to move the esp partition on the ssd, it was not allowing me to move it when I am booting directly in the ssd.
