### ISSUE TITLE
Help Needed: Changing boot logo

### ISSUE THREAD

**Issue by hardesh-peppermint** [jetsonhacks/bootFromExternalStorage#6]
Hi, 
Thanks for making the video and the repository. This helped me immensely. Hoping nvidia improves their documentation in the future. 

Is there any way to change the boot logo with this tool? I generated a new bmp.blob file and replaced it with existing bmp.blob in bootloader folder inside Linux_for_Tegra. But it didn't work. Any kind of help is appreciated. 

TIA,
Harshal

**Comment by jetsonhacks** [comment]
I don't know how to change the boot logo. Please ask this question in the official NVIDIA Jetson forums. You can start here: https://forums.developer.nvidia.com/t/boot-logo-not-changed/185102

**Comment by hardesh-peppermint** [comment]
Thanks for the prompt reply. I've referred to that thread in the past. Unfortunately, steps mentioned there didn't work for me. Thanks anyways. Closing this issue as it's not relevant.
